version: "3.1"
services:
    www:
        build: .
        container_name: www
        ports: 
            - "81:80"
        volumes:
            - ./www:/var/www/html
            - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        depends_on:
            - redis
        environment:
            XDEBUG_CLIENT_HOST: 172.17.0.1
            XDEBUG_CLIENT_PORT: 9001
            XDEBUG_CONFIG: idekey=PHPSTORM
            PHP_IDE_CONFIG: serverName=www-server
        networks:
            - www-network

    redis:
        image: redis:6.2
        container_name: app_redis
        ports:
            - "6379:6379"
        networks:
            - www-network

volumes:
    persistent: {}

networks:
    www-network:
        driver: "bridge"
